apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: opendatahub
  namespace: opendatahub
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-common
    name: odh-common
  - kustomizeConfig:
#      parameters:
#      - name: etcd_namespace
#        value: "{'endpoints': 'http://etcd.opendatahub:2379','root_prefix': 'modelmesh-serving'}"
      overlays:
      - odh-model-controller
      repoRef:
        name: manifests
        path: model-mesh
    name: model-mesh
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-dashboard
    name: odh-dashboard
  repos:
  - name: manifests
#    uri: https://api.github.com/repos/opendatahub-io/odh-manifests/tarball/pull/606/head
    uri: https://github.com/crobby/odh-manifests/tarball/mesh09
  version: master

